name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: pip install tox
      # Run tox using the version of Python in `PATH`
      - name: Run tests
        run: tox -e py
      - name: Run lint
        run: tox -e lint
      - name: Run type
        run: tox -e type